### ISSUE TITLE
yabsiotest.sh遗留

### ISSUE THREAD

**Issue by barton0426** [spiritLHLS/ecs#25]
单项测试trace后，根目录遗留了yabsiotest.sh文件，能清理掉吗?

**Comment by spiritLHLS** [comment]
没问题，晚上修复

**Comment by barton0426** [comment]
这怎么运行完把自己给干掉了- -
起码本体保留吧

**Comment by spiritLHLS** [comment]
改回去了，按理说不是意外退出不应该有残留的

**Comment by barton0426** [comment]
我还没测试 我上一条的意思是 正常运行完后 能把ecs本体保留 然后中间文件全部清理 那是最好的

**Comment by spiritLHLS** [comment]
> 我还没测试 我上一条的意思是 正常运行完后 能把ecs本体保留 然后中间文件全部清理 那是最好的

阿哲，没想到还有这种需求阿。。。一般都是测一遍就不再测了的，使用bash命令默认是不保持shell脚本的

晚点我改改说明吧，留存脚本
