### ISSUE TITLE
添加一个新的测速脚本至于第三方脚本区

### ISSUE THREAD

**Issue by Marionic0723** [spiritLHLS/ecs#27]
参考此贴：
https://www.nodeseek.com/post-5164-1 （中文）
https://lowendspirit.com/discussion/5812/comprehensive-speedtest-script-network-speed-xyz#latest （英语）

[综合速度测试脚本 | network-speed.xyz](https://network-speed.xyz/)

**Comment by spiritLHLS** [comment]
好的，晚些时候会加入第三方脚本区的测速方面分区中

**Comment by spiritLHLS** [comment]
已更新
