### ISSUE TITLE
可否增加一个参数关闭对 sysctl 的修改

### ISSUE THREAD

**Issue by DearTanker** [spiritLHLS/ecs#28]
默认执行脚本会对 sysctl 增加优化参数，这个可能有些人并不需要，希望可以在执行命令的时候增加一个参数以禁用优化。

**Comment by spiritLHLS** [comment]
今天晚些时候增加该选项

**Comment by spiritLHLS** [comment]
看了一遍源码，由于要保留菜单栏选项，所以无法通过外部再传输参数了，目前脚本的修改仅限于在原有的基础上增加设置，而不是修改已经有的设置，原有的sysctl参数不会被修改覆盖，这方面应该不会导致使用的问题，如果有请告知

**Comment by DearTanker** [comment]
在默认干净的系统，sysctl 默认没有任何参数。
执行命令后，sysctl 会带有脚本引入的参数，我个人觉得这种似乎不太恰当。

因为近期需要测试大量机器，对每台机器重新还原的话，发现这是一个不小的工作量。

**Comment by spiritLHLS** [comment]
唔，有道理

还有另一种折中的方法，优化只在测试期间生效，优化前记录原始默认值，测试完毕后删除优化变回默认值，这样两全其美

明天晚些时候看看，应该是可实现的

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/60b1800fa3718e53db522ca24d059990194f68c3

已修改脚本使得systl优化仅在测试期间起效果，执行完毕后重置回默认的设置，避免影响原系统环境
