### ISSUE TITLE
IOPS 计算可能有误

### ISSUE THREAD

**Issue by CornWorld** [spiritLHLS/ecs#29]
![image](https://github.com/spiritLHLS/ecs/assets/43746030/e757cb93-a706-4ed6-a564-be448c683330)
RT

**Comment by spiritLHLS** [comment]
lemonbench的原生问题，有空看看也许能修复

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/903474a4bc001655cf1779c74b561051f817cead

应该已修复，你看再测一次看看

**Comment by spiritLHLS** [comment]
之前那个写入IOPS的计算是通过将写入次数除以写入时间来得到的：

```
DiskTest_WriteIOPS="$(echo ${DiskTest_WriteTime} $3 | awk '{printf "%d\n",$2/$1}')"
```

这种计算方法在大部分情况下是有效的，但对于较小的块大小和较大的写入次数，有偏差

因为IOPS是对每秒钟的读/写操作次数，而块大小和写入次数会影响到每个操作的大小。当块大小较小且写入次数较大时，每个操作的大小会减小，导致IOPS计算的结果偏小。

为了准确地计算IOPS，已经将写入操作的大小（块大小）与写入时间结合，得到总的写入字节数，然后将其除以写入时间来计算IOPS，这思路应该没毛病了
