### ISSUE TITLE
出现“Virt-What Moudle install Failure!”错误 - 本地机器 - 非云服务器

### ISSUE THREAD

**Issue by iplaywind** [spiritLHLS/ecs#30]
出现了“Virt-What Moudle install Failure!”错误，以下是代码，请求协助。

Updating package management sources
Reading package lists...
Building dependency tree...
Reading state information...
dmidecode is already the newest version (3.3-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
checking sudo
checking tar
checking nc
adjusting the time
/dev/fd/63: line 648: chronyd: command not found
checking haveged
Synchronizing state of haveged.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable haveged
Removed /etc/systemd/system/sysinit.target.wants/haveged.service.
Synchronizing state of haveged.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable haveged
Created symlink /etc/systemd/system/sysinit.target.wants/haveged.service → /lib/systemd/system/haveged.service.
optimizing resource limits
optimizing sysctl configuration
/dev/fd/63: line 561: -a: command not found
CDN available, using CDN
Initializing Running Enviorment, Please wait ...
Checking Dependency ...
Virt-What Moudle install Failure! Try Restart Bench or Manually install it!

**Comment by spiritLHLS** [comment]
最近比较忙，可能9号晚上才能修复任何问题

**Comment by iplaywind** [comment]
> 是什么系统？

使用的是Debian11版本的系统，升腾C92主机（J1900处理器，4GB内存，16GB硬盘）。

**Comment by iplaywind** [comment]
> 最近比较忙，可能9号晚上才能修复任何问题

收到，感谢。机器配置很烂，用这个主要是测试一下整体机器的稳定性。

**Comment by Hisir0909** [comment]
> > 最近比较忙，可能9号晚上才能修复任何问题
> 
> 收到，感谢。机器配置很烂，用这个主要是测试一下整体机器的稳定性。

你找一下Virt-What的路径，把它加入PATH就好了

**Comment by spiritLHLS** [comment]
> > 是什么系统？
> 
> 使用的是Debian11版本的系统，升腾C92主机（J1900处理器，4GB内存，16GB硬盘）。

本地主机？

执行

```
which virt-what
```

看看路径是不是没有，如果没有尝试apt安装它，再查询，如果还是没有执行

```
sudo find / -name virt-what
```

看看是不是路径不对劲

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/52b45fa8fac741d81f49c32b93c6691df8720233

去除了virt-what的依赖，优化了基础信息查询部分，这样你那边应该没问题了

**Comment by iplaywind** [comment]
> [52b45fa](https://github.com/spiritLHLS/ecs/commit/52b45fa8fac741d81f49c32b93c6691df8720233)
> 
> 去除了virt-what的依赖，优化了基础信息查询部分，这样你那边应该没问题了

收到，谢谢。今天休息，明天我试试看，十分感谢。
