### ISSUE TITLE
测试结果支持英文显示

### ISSUE THREAD

**Issue by bitjerry** [spiritLHLS/ecs#33]
希望测试结果能显示英文

**Comment by spiritLHLS** [comment]
得花很多时间去重新适配英文，也许放年假或者别的长假我才有空进行该项优化

**Comment by blog2020** [comment]
> 得花很多时间去重新改装英文，也许放年假或者另外长假我继续空进行一项优化

没必要花时间去给测试结果整英文，浪费时间浪费精力。我看到有些脚本测试线路会显示是否优化线路，9929，cn2什么的，大佬不搞一下这个吗

**Comment by bitjerry** [comment]
> > 得花很多时间去重新改装英文，也许放年假或者另外长假我继续空进行一项优化
> 
> 没必要花时间去给测试结果整英文，浪费时间浪费精力。我看到有些脚本测试线路会显示是否优化线路，9929，cn2什么的，大佬不搞一下这个吗

如果你有别的请求, 请另开issue. 有没有必要增加英文你说的算?

**Comment by spiritLHLS** [comment]
> > 得花很多时间去重新改装英文，也许放年假或者另外长假我继续空进行一项优化
> 
> 没必要花时间去给测试结果整英文，浪费时间浪费精力。我看到有些脚本测试线路会显示是否优化线路，9929，cn2什么的，大佬不搞一下这个吗

融合怪依托于 https://github.com/zhanghanyun/backtrace 已经有对应分区了，有问题请去对应分区对应项目的GitHub仓库下的issues留言，本线程不解决你这种需求

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/f9b0d305b147a477f75da58ea4cf01c43b9d4405

已初步适配
