### ISSUE TITLE
Debain10运行报错（疑似证书过期导致SysBench安装失败）

### ISSUE THREAD

**Issue by wyrain** [spiritLHLS/ecs#35]
![image](https://github.com/spiritLHLS/ecs/assets/20262079/1a800f5f-5934-452f-9ce2-c479219ce189)

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/ecs/assets/103393591/f6608741-7dbd-4b5f-92fd-e62d0c0ab623)
有点奇怪，晚点我检查所有请求看看有没有忽略证书验证部分的内容，后台开证书没问题的

**Comment by spiritLHLS** [comment]
增加了二次重试的内容

https://github.com/spiritLHLS/ecs/commit/0be07fd6378e804ba25f219615d0e2e8b5334440
