### ISSUE TITLE
建议将默认 CPU 测试改为 Geekbench 5

### ISSUE THREAD

**Issue by gebederry** [spiritLHLS/ecs#36]
### 问题描述
当对 AMD 平台的小鸡进行测试时，gb5 的结果和 sysbench 差异过大，有时甚至达 4X。

下面是对同一只小鸡的测试
[Bench #1](https://paste.spiritlhl.net/code/pj9HVm.txt)
```shell
---------------------CPU测试--感谢lemonbench开源------------------------
 -> CPU 测试中 (Fast Mode, 1-Pass @ 5sec)
 1 线程测试(1核)得分: 		4694 Scores
 2 线程测试(多核)得分: 		9220 Scores
```
[Bench #2](https://paste.spiritlhl.net/code/u8LQrc.txt)
```shell
-----------------CPU测试--感谢yabs开源geekbench5测试--------------------
Test            | Value                        
Single Core     | 1124                          
Multi Core      | 1910                          
Full Test       | https://browser.geekbench.com/v5/cpu/22094131
```

建议佬和其它流行脚本一样使用 Geekbench 作为默认测试，感觉 gb 更全面专业，快速模式 sysbench 对 AMD 平台的 CPU 好像没怎么跑就出结果了。多数人都是直接跑默认的，会有点迷惑。

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/ecs/assets/103393591/6dc9caa8-7e18-434b-bebe-67531fb6a075)
默认说明里说过这些事情
![图片](https://github.com/spiritLHLS/ecs/assets/103393591/c5d7eeab-b429-4bfe-8e2d-273e658b704f)
有需求自行指定对应测试的CPU方式
geekbench无论何种测试起码2分钟40秒左右，太慢了

**Comment by gebederry** [comment]
> ![图片](https://private-user-images.githubusercontent.com/103393591/293526262-6dc9caa8-7e18-434b-bebe-67531fb6a075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzI3ODAsIm5iZiI6MTcwNDA3MjQ4MCwicGF0aCI6Ii8xMDMzOTM1OTEvMjkzNTI2MjYyLTZkYzljYWE4LTdlMTgtNDM0Yi1iZWJlLTY3NTMxZmI2YTA3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQwMTI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGYyMzJkYzE4M2IzOTAzNTk1YmRlMTY2MTQ4NmEwNGYxNTk4MjM1NjZmNWYyOWVmYmM0ZTIwNWNlNWFkMmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ByTdGfuWCrjtqjy50sycSQzyLNFrs0o8YTTP6AEprG4) 默认说明里说过这些事情 ![图片](https://private-user-images.githubusercontent.com/103393591/293526271-c5d7eeab-b429-4bfe-8e2d-273e658b704f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzI3ODAsIm5iZiI6MTcwNDA3MjQ4MCwicGF0aCI6Ii8xMDMzOTM1OTEvMjkzNTI2MjcxLWM1ZDdlZWFiLWI0MjktNGJmZS04ZTJkLTI3M2U2NThiNzA0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQwMTI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmMxYzI3YjMzZDc1ZDMxY2I3MTcyMjE3ZWE4N2YwYjU4ZmYxZTI4MGM0MjU0ZTk0OTJkMjJmYThiNjI1MDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hPP4KcHkO4KYEzP6LzSoVfcQdacynTdWCaCygy4VHwc) 有需求自行指定对应测试的CPU方式 geekbench无论何种测试起码2分钟40秒左右，太慢了

好吧，居然是因为觉得慢

**Comment by gebederry** [comment]
那这个 `sysbench` 就没意义了，因为它不准，无关快慢。

**Comment by spiritLHLS** [comment]
> 那这个 `sysbench` 就没意义了，因为它不准，无关快慢。

基于 https://github.com/akopytov/sysbench 创建的测试，没有意义只是针对你说的，准确度和geekbench没有可比性，geekbench不仅测了CPU，还受三缓/内存等因素影响了测试得分，如果你觉得不符合你的需求自行指定参数即可

`sysbench` 还有一个优点是可以保证绝大多数服务器都能跑的动测试，geekbench过于重型会导致很多服务器根本跑不动，测试时长过长，不符合大多数人需要一个 全面+快速 的测试需求，如果你有不同意见，你可以使用第三方分区别的作者的脚本
