### ISSUE TITLE
大佬能不能支持Alpine Linux

### ISSUE THREAD

**Issue by liuyinltemp** [spiritLHLS/ecs#37]
如题，Alpinex小巧，现在vps用的也不少了

**Comment by spiritLHLS** [comment]
只能说非常难，太多包无法通过命令安装了

**Comment by spiritLHLS** [comment]
已加入开发计划 https://github.com/users/spiritLHLS/projects/2

**Comment by spiritLHLS** [comment]
https://t.me/spiritlhl/227

初步适配
