### ISSUE TITLE
下载测速坏掉了么

### ISSUE THREAD

**Issue by dong-dong6** [spiritLHLS/ecs#38]
只有上传的速度

**Comment by dong-dong6** [comment]
![image](https://github.com/spiritLHLS/ecs/assets/73739354/1eb26991-623e-40c8-8c98-86840b89a33f)

**Comment by spiritLHLS** [comment]
测的国内服务器会出现这种问题，测国外服务器不会，这里使用的speedtest-go，你可以找官方的别的脚本再测测
