### ISSUE TITLE
脚本自带的更新检测无效

### ISSUE THREAD

**Issue by zzxqd** [spiritLHLS/ecs#39]
版本检测更新一直无效
![图片](https://github.com/spiritLHLS/ecs/assets/23022401/10bc7639-cf73-4abd-889e-21ad798dbce5)

查看了脚本 发现是取的ver的行数不对，取值是从第8行取，实际值的定义在7行
![图片](https://github.com/spiritLHLS/ecs/assets/23022401/4f11e4e9-cfcd-4d8f-bc23-df22797ca244)
![图片](https://github.com/spiritLHLS/ecs/assets/23022401/f652731e-8186-48ec-9234-3aabe7ba17b6)

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/6c524cafb7242cfd1ebab11cbbc8442acf6103ee

已修复，估计是先前哪次更新修改过前几行导致的错误

**Comment by zzxqd** [comment]
> [6c524ca](https://github.com/spiritLHLS/ecs/commit/6c524cafb7242cfd1ebab11cbbc8442acf6103ee)
> 
> 已修复，估计是先前哪次更新修改过前几行导致的错误

我觉得不用修改取version的行数，直接就在第8行定义version更好点，这样之前有问题的版本也能检测到最新的version并进行更新。😂
