### ISSUE TITLE
windows vps的用wsl的Ubuntu24版本运行，卡在后台任务执行完毕就不动了(疑似带宽小环境依赖下载缓慢所导致)

### ISSUE THREAD

**Issue by spromaxultra** [spiritLHLS/ecs#40]
![image](https://github.com/spiritLHLS/ecs/assets/160609279/90cec4c4-cbad-4d44-8c3b-1a324c20bad4)

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/ecs/assets/103393591/bb33e744-ec1d-46ec-bff4-7c7b8afb981c)

估计你的带宽很小，在下这些环境依赖的时候耗时需要很久，而你没有继续等下去，我猜测你是在国内机器上测
