### ISSUE TITLE
建议: 以GB6作为 cpu 跑分工具

### ISSUE THREAD

**Issue by tanpengsccd** [spiritLHLS/ecs#41]
建议: 以GB6作为 cpu 跑分工具.
gb6 gb5跑分使用的人更多. 比较好参考.

**Comment by tanpengsccd** [comment]
sysbench 主要是使用的人不多,生态较差, 能查到的排行比较少. 
如果不能查到分数,那么就算是能快速拿到跑分 意义也不是特别大.

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/issues/36

相关问题已经讨论过了，如果你有需求可用使用参数进行指定。
