### ISSUE TITLE
为什么我运行脚本,流媒体都不输出?

### ISSUE THREAD

**Issue by jsjcjsjc** [spiritLHLS/ecs#42]
`
以下测试的解锁地区是准确的，但是不是完整解锁的判断可能有误，这方面仅作参考使用
----------------Netflix-----------------
[IPV4]
您的出口IP可以使用Netflix，但仅可看Netflix自制剧
NF所识别的IP地域信息：新加坡
[IPV6]
您的出口IP完整解锁Netflix，支持非自制剧的观看
NF所识别的IP地域信息：新加坡
----------------Youtube-----------------
[IPV4]
连接方式: Youtube Video Server
视频缓存节点地域: 新加坡 新加坡/樟宜  (SIN11S18)
Youtube识别地域: 新加坡(SG)
[IPV6]
连接方式: Youtube Video Server
视频缓存节点地域: 新加坡 新加坡/樟宜  (SIN11S18)
Youtube识别地域: 新加坡(SG)
---------------DisneyPlus---------------
[IPV4]
当前出口所在地区解锁DisneyPlus
区域：SG 区
[IPV6]
当前出口所在地区解锁DisneyPlus
区域：SG 区
解锁Netflix，Youtube，DisneyPlus上面和下面进行比较，不同之处自行判断
----------------流媒体解锁--感谢RegionRestrictionCheck开源--------------
 以下为IPV4网络测试，若无IPV4网络则无输出
 以下为IPV6网络测试，若无IPV6网络则无输出
---------------TikTok解锁--感谢lmc999的源脚本及fscarmen PR--------------
 Tiktok Region:         【SG】`

一直提示,测试了好几台都这样,只有go版本可以
```
 以下为IPV4网络测试，若无IPV4网络则无输出
 以下为IPV6网络测试，若无IPV6网络则无输出
```

运行的是这个命令
`curl -L https://github.com/spiritLHLS/ecs/raw/main/ecs.sh -o ecs.sh && chmod +x ecs.sh && bash ecs.sh -m 1`

**Comment by spiritLHLS** [comment]
建议单独使用对应项目 https://github.com/lmc999/RegionRestrictionCheck 进行测试，但大概率还是会有问题，因为shell版本就是下了这个项目的shell执行报错不显示罢了
使用golang重构的融合怪 https://github.com/oneclickvirt/ecs 进行测试应该无此问题，所有测试项目均重构

**Comment by jsjcjsjc** [comment]
> [github.com/lmc999/RegionRestrictionCheck](https://github.com/lmc999/RegionRestrictionCheck)

确实~~
