### ISSUE TITLE
建议增加检测是否可以解锁Meta.ai的功能

### ISSUE THREAD

**Issue by kevin5872** [spiritLHLS/ecs#46]
最近发现Meta推出的AI助手Meta AI挺有意思的,但好像有地区限制。链接：[meta.ai](https://www.meta.ai)

我在想能不能在这个测试脚本里加一个检测是否可以访问/解锁Meta AI的功能？这样我们选择VPS的时候就能知道哪些IP可以用Meta AI了。

**Comment by spiritLHLS** [comment]
由于是调用的项目，在本项目的shell版本无解

但你可以使用GO重构的本项目：https://github.com/oneclickvirt/ecs

里面包含了你需求的实现
