### ISSUE TITLE
yabs 下载卡在 0%

### ISSUE THREAD

**Issue by Chun-QiuCC** [spiritLHLS/ecs#47]
大陆机器yabs 下载卡在 0%，其它能正常下载
![7a5c0267-fad2-4823-a5d6-4ba9d3d7ae9f](https://github.com/user-attachments/assets/d1b9b6e3-e3e4-4e85-b50b-f64e6ac16f6e)

**Comment by spiritLHLS** [comment]
建议使用goecs进行测试 Go版本不会出现依赖问题 
https://github.com/oneclickvirt/ecs
