### ISSUE TITLE
除0错误？

### ISSUE THREAD

**Issue by hoky** [spiritLHLS/ecs#48]
No match for argument: sysbench
Error: Unable to find a match: sysbench
Sysbench Module install Failure, trying compile modules ...
Release Detected: centos
Preparing compile enviorment ...
warning: Signature not supported. Hash algorithm SHA1 not available.
Last metadata expiration check: 0:05:56 ago on Mon Oct 21 13:51:13 2024.
Package epel-release-9-7.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
warning: Signature not supported. Hash algorithm SHA1 not available.
Last metadata expiration check: 0:05:56 ago on Mon Oct 21 13:51:13 2024.
Package wget-1.21.1-8.el9.x86_64 is already installed.
Package curl-7.76.1-31.el9.x86_64 is already installed.
Package make-1:4.3-8.el9.x86_64 is already installed.
Package gcc-11.5.0-2.el9.x86_64 is already installed.
Package gcc-c++-11.5.0-2.el9.x86_64 is already installed.
Package automake-1.16.2-8.el9.noarch is already installed.
Package libtool-2.4.6-46.el9.x86_64 is already installed.
Package pkgconf-pkg-config-1.7.3-10.el9.x86_64 is already installed.
Package libaio-devel-0.3.111-13.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Downloading Source code (Version 1.0.20)...
下载进度：
sysbench             [#                                                 ]   0%
Dependencies resolved.ent_size * 100 / total_size: division by 0 (error token is "total_size")
Nothing to do.90: current_size * 100 / total_size: division by 0 (error token is "total_size")
Complete!ine 709: final_size * 100 / total_size: division by 0 (error token is "total_size")
Downloading Source code (Version 1.0.20)...

**Comment by spiritLHLS** [comment]
大概是下载识别不到任何下载到的文件大小，有空我优化一下识别和输出的流程

**Comment by spiritLHLS** [comment]
有问题时建议使用 https://github.com/oneclickvirt/ecs 进行测试

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecs/commit/eb354bd6f0e879889e7b4b6256225eddbbde5f8a 
已修复
